apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghjk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghjk
  template:
    metadata:
      labels:
        app: ghjk
    spec:
      containers:
      - image: okteto.dev/ghjk:latest
        name: ghjk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2605407-c006-4fac-af40-56ff9ef0e07e"
        - name: Vless_Path
          value: "/vl5gfd55"
        - name: Vmess_UUID
          value: "2605407-c006-4fac-af40-56ff9ef0e07e"
        - name: Vmess_Path
          value: "/vmhg666"
        - name: Share_Path
          value: "/v2link"
